name: example
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0-alpha-1+3

environment:
  sdk: ^3.9.2

dependencies:
  collection: ^1.19.1
  envied: ^1.3.2
  flutter:
    sdk: flutter
  flutter_crosspay:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  envied_generator: ^1.3.2
  build_runner: ^2.10.5

flutter:
  uses-material-design: true
