name: flutter_crosspay
description: Cross platform in app purchase plugin. Supports all flutter platforms. Desktop and web are supported through Stripe. Developed by Maxint Inc.
version: 0.1.0
homepage: https://github.com/maxint-app/crosspay

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.19.1
  crypto: ^3.0.7
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_client_sse: ^2.0.3
  freezed_annotation: ^3.1.0
  in_app_purchase: ^3.2.3
  in_app_purchase_android: ^0.4.0+8
  in_app_purchase_storekit: ^0.4.7
  json_annotation: ^4.9.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  freezed: ^3.2.4
  json_serializable: ^6.11.4
  build_runner: ^2.10.5
